version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - "./:/app/build"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:13.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=PGADMIN_DEFAULT_PASSWORD
      - PGADMIN_LISTEN_PORT=5050
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "${PGADMIN_LISTEN_PORT:-5050}:${PGADMIN_LISTEN_PORT:-5050}"
    depends_on:
      - postgres
    links:
      - postgres

volumes:
  db_data: {}
