# Generated by Django 3.2.3 on 2021-07-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_auto_20210701_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='type',
        ),
    ]
