# Generated by Django 3.2.3 on 2021-07-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0009_analytics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together={('path', 'request_method')},
        ),
    ]
