# Generated by Django 3.2.3 on 2021-07-04 14:37

from django.db import migrations


def forwards(apps, schema_editor):
    Rate = apps.get_model('currency', 'Rate')
    Bank = apps.get_model('currency', 'Bank')

    privatbank = Bank.objects.create(
        name='PrivatBank',
        url='https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5',
        original_url='https://www.privat24.ua/',
    )
    for rate in Rate.objects.all():
        if 'privatbank' in rate.source.lower():
            rate.bank = privatbank

        rate.save()



def backwards(apps, schema_editor):
    # Post = apps.get_model('blog', 'Post')
    print('HELLO FROM BACKWARDS!')


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_auto_20210704_1425'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
