# Generated by Django 3.2.3 on 2021-07-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0015_alter_bank_code_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='source',
        ),
    ]
